name: R-CMD-check-and-coverage

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R package dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          install.packages(c("covr", "testthat"))

      - name: Run tests
        run: |
          Rscript -e 'devtools::test()'

      - name: Upload coverage to Codecov
        run: |
          Rscript -e 'covr::codecov()'
